import React from "react";
import Task from "~/components/Tasks/Task";
import { prisma } from "~/lib/prisma";

type Params = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({ params }: Params) {
  const task = await prisma.task.findUnique({
    where: {
      slug: params.slug,
    },
    select: {
      name: true,
    },
  });

  return {
    title: task?.name,
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

const SingleTaskPage = async ({ params }: Params) => {

  // const taskName = decodeURIComponent(params.name);
  const task = await prisma.task.findUnique({
    where: {
      slug: params.slug,
    },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          image: true,
        },
      },
      assignedTo: {
        include: {
          user: {
            select: {
              id: true,
              name: true,
              image: true,
            },
          },
        },
      },
      TaskNote: {
        include: {
          createdBy: {
            select: {
              id: true,
              name: true,
              image: true,
            },
          },
        },
      },
      TaskFiles: {
        select: {
          id: true,
          taskId: true,
          url: true,
        },
      }
    },
  });

  return (
    task && (
      <div className="py-10" suppressHydrationWarning>
        <Task task={task} admin={true} />
      </div>
    )
  );
};

export default SingleTaskPage;
