import React from "react";
import Task from "~/components/Tasks/Task";
import { prisma } from "~/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "~/server/auth";

type Params = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({ params }: Params) {
  const task = await prisma.task.findUnique({
    where: {
      slug: params.slug,
    },
    select: {
      name: true,
    },
  });

  return {
    title: task?.name,
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

const SingleTaskPage = async ({ params }: Params) => {
  const session = await getServerSession(authOptions);
  const isAdmin = session?.user.role === "admin" ? true : false;

  const task = await prisma.task.findUnique({
    where: {
      slug: params.slug,
    },
    include: {
      createdBy: {
        select: {
          id: true,
          name: true,
          image: true,
        },
      },
      assignedTo: {
        include: {
          user: {
            select: {
              id: true,
              name: true,
              image: true,
            },
          },
        },
      },
      TaskNote: {
        include: {
          createdBy: {
            select: {
              id: true,
              name: true,
              image: true,
            },
          },
        },
      },
      TaskFiles: {
        select: {
          id: true,
          taskId: true,
          url: true,
        },
      },
    },
  });

  return (
    task && (
      <div className="py-10" suppressHydrationWarning>
        <Task task={task} admin={isAdmin} />
      </div>
    )
  );
};

export default SingleTaskPage;
