import "~/styles/globals.css";
import React from "react";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { EdgeStoreProvider } from "~/lib/edgestore";
import { getServerSession } from "next-auth/next";
import { authOptions } from "~/server/auth";
import { ThemeProvider } from "~/components/theme-provider";
import { Toaster } from "react-hot-toast";
import SessionProvider from "~/lib/session";
import { SidebarProvider, SidebarInset } from "~/components/ui/sidebar";
import Header from "~/components/elements/Header/Header";
import { AppSidebar } from "~/components/elements/Sidebar/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  const messages = await getMessages();

  const session = await getServerSession(authOptions);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`min-h-screen font-sans ${inter.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <SessionProvider session={session}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <EdgeStoreProvider>
                <SidebarProvider>
                  <AppSidebar />
                  <SidebarInset>
                    <Header />
                    <main className="container pt-20">
                      {React.cloneElement(children as React.ReactElement, {
                        session,
                      })}
                    </main>
                  </SidebarInset>
                </SidebarProvider>
              </EdgeStoreProvider>
              <Toaster />
            </ThemeProvider>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
